/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      colors: {
        'mono-50': 'rgb(var(--color-mono-50) / <alpha-value>)',
        'mono-100': 'rgb(var(--color-mono-100) / <alpha-value>)',
        'mono-200': 'rgb(var(--color-mono-200) / <alpha-value>)',
        'mono-300': 'rgb(var(--color-mono-300) / <alpha-value>)',
        'mono-400': 'rgb(var(--color-mono-400) / <alpha-value>)',
        'mono-500': 'rgb(var(--color-mono-500) / <alpha-value>)',
        'mono-600': 'rgb(var(--color-mono-600) / <alpha-value>)',
        'mono-700': 'rgb(var(--color-mono-700) / <alpha-value>)',
        'mono-800': 'rgb(var(--color-mono-800) / <alpha-value>)',
        'mono-900': 'rgb(var(--color-mono-900) / <alpha-value>)',
        'mono-950': 'rgb(var(--color-mono-950) / <alpha-value>)',
        'red-50': 'rgb(var(--color-red-50) / <alpha-value>)',
        'red-100': 'rgb(var(--color-red-100) / <alpha-value>)',
        'red-200': 'rgb(var(--color-red-200) / <alpha-value>)',
        'red-600': 'rgb(var(--color-red-600) / <alpha-value>)',
        'red-700': 'rgb(var(--color-red-700) / <alpha-value>)',
        'red-800': 'rgb(var(--color-red-800) / <alpha-value>)',
        'green-50': 'rgb(var(--color-green-50) / <alpha-value>)',
        'green-100': 'rgb(var(--color-green-100) / <alpha-value>)',
        'green-200': 'rgb(var(--color-green-200) / <alpha-value>)',
        'green-300': 'rgb(var(--color-green-300) / <alpha-value>)',
        'green-400': 'rgb(var(--color-green-400) / <alpha-value>)',
        'green-500': 'rgb(var(--color-green-500) / <alpha-value>)',
        'green-600': 'rgb(var(--color-green-600) / <alpha-value>)',
        'amber-50': 'rgb(var(--color-amber-50) / <alpha-value>)',
        'amber-100': 'rgb(var(--color-amber-100) / <alpha-value>)',
        'amber-200': 'rgb(var(--color-amber-200) / <alpha-value>)',
        'amber-400': 'rgb(var(--color-amber-400) / <alpha-value>)',
        'amber-600': 'rgb(var(--color-amber-600) / <alpha-value>)',
        'amber-800': 'rgb(var(--color-amber-800) / <alpha-value>)',
        'blue-50': 'rgb(var(--color-blue-50) / <alpha-value>)',
        'blue-100': 'rgb(var(--color-blue-100) / <alpha-value>)',
        'blue-200': 'rgb(var(--color-blue-200) / <alpha-value>)',
        'blue-400': 'rgb(var(--color-blue-400) / <alpha-value>)',
        'blue-600': 'rgb(var(--color-blue-600) / <alpha-value>)',
        'blue-800': 'rgb(var(--color-blue-800) / <alpha-value>)',
      },
      boxShadow: {
        'glow-green': '0 0 15px rgb(var(--color-green-400) / 0.2)',
        'glow-green-lg': '0 0 20px rgb(var(--color-green-400) / 0.2)',
        'glow-green-xl': '0 0 30px rgb(var(--color-green-400) / 0.4)',
        'glow-green-sm': '0 0 10px rgb(var(--color-green-400) / 0.1)',
        'glow-green-icon': '0 0 15px rgb(var(--color-green-400) / 0.1)',
        'glow-green-dot': '0 0 5px rgb(var(--color-green-400) / 0.8)',
        'glow-green-bar': '0 0 10px rgb(var(--color-green-400) / 0.4)',
        'drawer-deep': '0 0 50px rgba(0, 0, 0, 0.5)',
      },
    }
  },
  plugins: []
}
